### ISSUE TITLE
Am i doing something wrong or is this not opening properly?

### ISSUE THREAD

**Issue by cameronmckirdy** [open-stage/blender-dmx#100]
Hi all, 

Excuse the possible Noob nature of this post! - Ive installed the plugin before and it all worked fine but since updated blender i'm having this issue where nothing pops out in the side tab. (see the image)    

![image](https://github.com/open-stage/blender-dmx/assets/10037548/5562bc42-2ad5-485b-a4f2-928571c73d52)

have i installed something wrong or is this a bug? 

Using 1.0.8 on blender 4.0

**Comment by vanous** [comment]
Please use discord for questions like this. Thank you
