### ISSUE TITLE
fixture stops processing data

### ISSUE THREAD

**Issue by fgiering** [open-stage/blender-dmx#105]
### Steps to reproduce:

1. create fixture
2. enable ArtNet Input in blender-dmx
3. send ArtNet Data from Light-Control
4. check if receiving
5. create volume Box
6. change renderer to cycles
7. change back to evee

### expectedt result:
ArtNet Data is processed continous

### actual result:
need to select fixture to activate it again (and sometimes need to deactivate and reactivate ArtNet Input)

### Environment:
blender-dmx 1.1.0
Blender 4.0.2

**Comment by vanous** [comment]
I think this is an issue with your computer or maybe operating system? I have not seen such issue and i also tested your description and for me, data is always received and processed. I even recorded this to show you but the file is over 10MB limit of Github, so i cannot post it here.

**Comment by vanous** [comment]
Uh, i pushed it a bit too small but here is my video of your description. See if you perhaps do something different. I do not have ArtNet pre-programmed, so i just lean over and move a fader to have the DMX to move...

https://github.com/open-stage/blender-dmx/assets/3680926/6b36aa26-7a78-47c0-81a2-5131f83d0c95

**Comment by fgiering** [comment]
Hm. Interesting. Could be a problem with the dmx-software I use. blender-dmx is not replying like an ArtNet-Node, right?
https://art-net.org.uk/how-it-works/discovery-packets/

**Comment by vanous** [comment]
This would be unrelated and btw BlenderDMX does support ArtPollReply.

**Comment by vanous** [comment]
What's the DMX software you are using? Can you somehow check if it keeps sending the data out all the time? Do you have it running on the same computer or on some other one? For the test to confirm where your issue comes from, you can send some values from your phone, in case you are using some software on the same computer and it has a tendency to stop outputting...

**Comment by vanous** [comment]
I tested if ArtPollReply is sent when/after some DMX data is flowing in and in my tests, this keeps working. I am afraid i cannot help here, try to troubleshoot your Art-Net sending software. You can also check with other users in the Discord chat.
