### ISSUE TITLE
grandMA3 MA-Net-Support

### ISSUE THREAD

**Issue by EinfachKonrad** [open-stage/blender-dmx#116]
Support for the viz-key to use the viz without having to have thounsands of parameters

**Comment by vanous** [comment]
Well, that would be interesting but most likely it's not possible as it probably depends on not open sourced applications. What I mean is - if BlenderDMX receives the data, it could re-stream it as DMX so these "MA partners" are most likely very carefully vetted by MA. But feel free to research and contribute an implementation.
