### ISSUE TITLE
Enabling Add-on provides error

### ISSUE THREAD

**Issue by huitingloke** [open-stage/blender-dmx#124]
<img width="646" alt="Screenshot 2024-02-24 at 12 18 41 PM" src="https://github.com/open-stage/blender-dmx/assets/96629569/5fcdd78f-7cbc-4ac9-96fe-73dbaafb7dc8">

Installed Blender DMX and dragged zip file to Add-ons, gave this error when I tried to click the checkbox.

**Comment by vanous** [comment]
Hello, what version of Blender are you using? You need at least Blender 3.4 .

**Comment by vanous** [comment]
From the screenshot, you are on Blender 2.9 , it will not work, you need higher version.
