### ISSUE TITLE
Can't enable it in the Addon menu

### ISSUE THREAD

**Issue by memoabuser** [open-stage/blender-dmx#15]
Hello, thank you for that great Addon, I'm really excited to use it.
I got that issue when I try to enable it in the Addon menu:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'blenderDMX-0'

I'm using blender 3.3 LTS, on Windows

**Comment by vanous** [comment]
Hello @memoabuser ,

i just tested on Windows with Blender 3.4 and BlenderDMX works correctly for me. From your error message, it seems some kind of path or naming issue, maybe some kind of configuration error. Are you still having this issue?

**Comment by vanous** [comment]
This is an issue with the addon not being installed in the `dmx` directory. Make sure to do so, as per [documentation](https://github.com/open-stage/blender-dmx/#download--install).
