### ISSUE TITLE
Blender getting crashed

### ISSUE THREAD

**Issue by surajchauhan6631** [open-stage/blender-dmx#177]
### Please confirm that;

- [X] I have checked the [documentation](https://blenderdmx.eu/docs/faq/), and I didn't find a solution to my problem / an answer to my question.
- [X] I have searched the [issues](https://github.com/open-stage/blender-dmx/issues), and I didn't find a solution to my problem / an answer to my question.
- [X] I have asked in the user group on [Discord](https://discord.gg/FQVVyc45T9) for ideas and solutions.

### What is your Blender version?

4.1

### What operating system are you using Blender on?

Windows

### What happened?

Blender getting crashed or not responding whenever i cilck on the enable artnet tick box .

**Comment by vanous** [comment]
There's a thread open in discord, closing this as a duplicate.
