### ISSUE TITLE
Industry Compatible keymap issue

### ISSUE THREAD

**Issue by qlcplusme** [open-stage/blender-dmx#235]
### Please confirm that;

- [X] I have checked the [documentation](https://blenderdmx.eu/docs/faq/), and I didn't find a solution to my problem / an answer to my question.
- [X] I have searched the [issues](https://github.com/open-stage/blender-dmx/issues), and I didn't find a solution to my problem / an answer to my question.
- [X] I have asked in the user group on [Discord](https://discord.gg/FQVVyc45T9) for ideas and solutions and have waited for someone to respond.

### What is your Blender version?

4.2.3

### What operating system are you using Blender on?

Linux

### What happened?

The blender-dmx shortcuts are already used under industry compatible layout, so they do not work.
It seems also not possible to change them, every time I reload a file in Blender the shortcuts are restored to their original value.

**Comment by vanous** [comment]
Hello, yes, at this point it is not possible to change the shortcuts. You can come to discuss this in the discord forum, as requested in the issue template, thank you very much!
