### ISSUE TITLE
Artnet Not working

### ISSUE THREAD

**Issue by eventsjakob** [open-stage/blender-dmx#24]
Hello, I have spent the day working out your amazing software - I have hit a wall, Enabling Artnet Input just stays on either waiting for data or opening port (I can't quite remember the message, i'm not with my console right now).

I have used the Artnetominator on my PC to make sure my lighting desk can see, and yes it can. I'm Using and Avolites Tiger Touch.

Is there anything else within Blender I might need to do? Using Blender 3.3...would updating the software help?

**Comment by vanous** [comment]
Thank you for the kind words, appreciated.

For future readers: I would suggest to use a protocol which allows multiple receivers on one computer and is not requiring IP address settings - for that, BlenderDMX includes sACN receiver.

As for Artnet input, this is a configuration issue, you can get some help in the discord chat (as you did already :), so i will close this now).
