### ISSUE TITLE
Files created on alpha/beta won't work at vanilla

### ISSUE THREAD

**Issue by hugoaboud** [open-stage/blender-dmx#28]
## Description

When trying to open a file created at earlier versions, BlenderDMX breaks in many different ways.

This happens mostly due to the new structure that finds the GDTF "root geometry" and flags it as a "Root" object. On earlier versions, we would assume an object called "Body" as the fixture root.
This should be seen especially on BlenderDMX GDTFs, which were created under this assumption.

## Workaround

There's no safe way to make this backwards compatible, so we're not solving it.
However, the following script should fix most cases:

- On Blender, go to the `Scripting` tab.
- Click the `+ New` button.
- Paste the script and run it.

```python
#
# [BlenderDMX v1]
# 
# Update Fixtures from earlier versions.
# Please note this might not work for some fixtures.
#

import bpy
dmx = bpy.context.scene.dmx

for fixture in dmx.fixtures:
    for obj in fixture.objects:
        if (obj.name == 'Body'):
            obj.name = 'Root'
    
    # This line refers to the issue #26, and should not be necessary on later versions
    fixture.emitter_materials.clear()

    fixture.build(
        fixture.name,
        fixture.profile,
        fixture.mode,
        fixture.universe,
        fixture.address,
        fixture.gel_color,
        fixture.display_beams
    )
```

**Comment by hugoaboud** [comment]
I'm keeping the Issue open for feedback on the patch. If necessary, I'll make updates to it.

**Comment by eventsjakob** [comment]
I can confirm this has worked, no more error messages.

Artnet is still not working in V1.0

**Comment by vanous** [comment]
Seems like no more issues on this. I will close this now.
