### ISSUE TITLE
Wrong translation license

### ISSUE THREAD

**Issue by comradekingu** [open-stage/blender-dmx#36]
https://hosted.weblate.org/projects/blenderdmx/main/#information
says **LGPLv3**-or-later, whereas
https://github.com/open-stage/blender-dmx/blob/main/LICENSE
says **GPLv3**-or-later

Can be changed in
https://hosted.weblate.org/settings/blenderdmx/main/
and
https://hosted.weblate.org/settings/blenderdmx/glossary/

**Comment by vanous** [comment]
fixed
